import { LockConfig } from './types';

export const LOCK_PRESETS: LockConfig[] = [
  {
    id: 'tutorial-lock',
    name: '木製のミニ宝箱・練習用鍵',
    difficulty: 'novice',
    sweetSpotCenter: 90, // default center position
    sweetSpotWidth: 16,  // very wide tolerance
    durabilityFactor: 0.3, // breaks very slowly
    description: '初心者のための鍵。ピンの配列が目視できる、訓練用の透明アクリルシリンダー。',
    isUnlocked: true,
    scoreBonus: 100,
  },
  {
    id: 'leather-bag',
    name: '革製の古びた旅人カバン',
    difficulty: 'novice',
    sweetSpotCenter: 115,
    sweetSpotWidth: 14,
    durabilityFactor: 0.4,
    description: '擦り切れた古い革鞄の留め具。鍵自体は単純で乱雑な作りですが、少しだけ引っかかりがあります。',
    isUnlocked: false,
    scoreBonus: 150,
  },
  {
    id: 'simple-padlock',
    name: '錆びた古い南京錠',
    difficulty: 'novice',
    sweetSpotCenter: 45,
    sweetSpotWidth: 12,
    durabilityFactor: 0.5,
    description: '古い倉庫にかかっていた南京錠。内部が劣化しており、少し探るだけで開くスロットが見つかります。',
    isUnlocked: true,
    scoreBonus: 200,
  },
  {
    id: 'rusted-iron-gate',
    name: '墓地の錆びた鉄格子の門',
    difficulty: 'apprentice',
    sweetSpotCenter: 30,
    sweetSpotWidth: 10,
    durabilityFactor: 0.7,
    description: '風雨にさらされた地下墓地入り口の鍵。錆がシリンダー内に詰まっており、回す際の感触が著しく鈍いです。',
    isUnlocked: false,
    scoreBonus: 300,
  },
  {
    id: 'wooden-drawer',
    name: '宿屋の木製引き出し',
    difficulty: 'apprentice',
    sweetSpotCenter: 135,
    sweetSpotWidth: 9,
    durabilityFactor: 0.8,
    description: '一般的な木製家具。作りはそこそこですが、無理にこじ開けるとピックに負荷がかかります。',
    isUnlocked: false,
    scoreBonus: 400,
  },
  {
    id: 'merchant-safe',
    name: '商人ギルドの鉄製卓上金庫',
    difficulty: 'apprentice',
    sweetSpotCenter: 165,
    sweetSpotWidth: 8,
    durabilityFactor: 0.9,
    description: '街の商会が愛用するスチール製の金庫。内部シリンダーの咬み合わせが深く、慎重な操作が求められます。',
    isUnlocked: false,
    scoreBonus: 500,
  },
  {
    id: 'iron-chest',
    name: '鉄製の頑丈なチェスト',
    difficulty: 'adept',
    sweetSpotCenter: 75,
    sweetSpotWidth: 6,
    durabilityFactor: 1.2,
    description: '盗賊団が金品の保管に使っていたもの。シリンダーが頑丈で、スイートスポットが比較的狭いです。',
    isUnlocked: false,
    scoreBonus: 800,
  },
  {
    id: 'prison-passage',
    name: '廃牢獄の秘密の鉄蓋扉',
    difficulty: 'adept',
    sweetSpotCenter: 60,
    sweetSpotWidth: 5,
    durabilityFactor: 1.4,
    description: '隠された旧地下牢からの脱出路。二重のピン構造を持っており、勢いよくテンションをかけると即座にロックされます。',
    isUnlocked: false,
    scoreBonus: 1000,
  },
  {
    id: 'mansion-door',
    name: '貴族の屋敷の執務室のドア',
    difficulty: 'expert',
    sweetSpotCenter: 155,
    sweetSpotWidth: 3.5,
    durabilityFactor: 2.0,
    description: '特注の真鍮製シリンダー。微細な手の感覚を頼りにピックを回す必要があり、急激なテンションは即破損に繋がります。',
    isUnlocked: false,
    scoreBonus: 1500,
  },
  {
    id: 'mage-bookcase',
    name: '王宮魔術師の禁書棚',
    difficulty: 'expert',
    sweetSpotCenter: 140,
    sweetSpotWidth: 2.8,
    durabilityFactor: 2.5,
    description: 'かすかに魔力を感じる高硬度のシリンダー。極小のブレでもピックに強い負荷が蓄積される魔法仕掛けの鍵穴。',
    isUnlocked: false,
    scoreBonus: 2000,
  },
  {
    id: 'ancient-vault',
    name: '古代遺跡の地下大金庫',
    difficulty: 'master',
    sweetSpotCenter: 110,
    sweetSpotWidth: 1.5,
    durabilityFactor: 3.5,
    description: '数百年前に作られた精密なドワーフの鍵。強烈なテンション耐性を備えており、奇跡的な正確さが必要です。',
    isUnlocked: false,
    scoreBonus: 3000,
  },
  {
    id: 'forbidden-archives',
    name: '封印された禁忌書庫の超鉄扉',
    difficulty: 'master',
    sweetSpotCenter: 95,
    sweetSpotWidth: 1.1,
    durabilityFactor: 4.2,
    description: '帝国の闇の歴史を封じた保管庫。シリンダーの遊び(あそび)が全くなく、針に糸を通すような指先の精密さが必要です。',
    isUnlocked: false,
    scoreBonus: 4500,
  },
  {
    id: 'omega-box',
    name: '古代遺物「オメガ・コア」の次元函',
    difficulty: 'master',
    sweetSpotCenter: 20,
    sweetSpotWidth: 0.7,
    durabilityFactor: 5.5,
    description: '人類の理解を超えたロストテクノロジーの結晶。わずか1ピクセルの狂いも許さず、誤った角度で挑めば即座にピックが崩壊します。',
    isUnlocked: false,
    scoreBonus: 8000,
  }
];

export const TUTORIAL_PINS = [
  { id: 1, targetY: 60, currentY: 0, isLocked: false, label: 'ピン 1' },
  { id: 2, targetY: 40, currentY: 0, isLocked: false, label: 'ピン 2' },
  { id: 3, targetY: 75, currentY: 0, isLocked: false, label: 'ピン 3' },
  { id: 4, targetY: 30, currentY: 0, isLocked: false, label: 'ピン 4' },
  { id: 5, targetY: 55, currentY: 0, isLocked: false, label: 'ピン 5' },
];
